import psycopg2

db_name = os.environ("DB_NAME")
db_user = os.environ("DB_USER")
db_password = os.environ("DB_PASSWORD")
db = psycopg2.connect('dbname=' + db_name + ' user=' + db_user + ' password=' + db_password)
cursor = db.cursor()

cursor.execute("create sequence counter_users")
cursor.execute("create sequence counter_stores")
cursor.execute("create sequence unsub_code")
cursor.execute("create sequence group_ids")
cursor.execute("create sequence offer_ids")
cursor.execute("create sequence job_ids")
cursor.execute("create table endusers (acc_id int primary key default nextval('counter_users'), phonenumber bigint, msgval smallint, email text, fullname text, password text)")
cursor.execue("create table stores (acc_id int primary key default nextval('counter_stores'), name text, password text, waittime smallint, logo text, promo text, color int[3], highlight int[3], primchan int, template text, sopchode varchar(5), ip text)")
cursor.execute("create table groups (name text, owner int references stores(acc_id), group_id int primary key default nextval('group_ids'))")
cursor.execute("create table subscriptions (acc_id int references endusers(acc_id), groups int[] unsubs int[])")
cursor.execute("create table points (acc_id int references endusers(acc_id), stores int[], counts smallint[])")
cursor.execute("create table offers (offer_id int primary key default nextval('offer_ids'), group_owner int, name text, description text, expiration int, points int)")
cursor.execute("create table transactions (time int, acc_id int references endusers(acc_id), store int references stores(acc_id), notes text)")
cursor.execute("create table coupons (acc_id int references endusers(acc_id), code bigint, store_id int references stores(acc_id), offer_id int references offers(offer_id), exp int)")
cursor.execute("create table sessions (session_id character(40) primary key, atime timestamp without time zone not null default current_timestamp, data text)")
cursor.execute("create table redemptions (acc_id int references endusers(acc_id), store int references stores(acc_id), time timestamp default current_timestamp, name text)")
cursor.execute("create table mail_jobs (job_id int primary key default nextval('job_ids'), mailer_id int references stores(acc_id), subject varchar(3), header varchar(30), message varchar(140), send int, recur int, offer int, ttype int, tinfo text, recur_count int)")
db.commit()
db.close()
